### ISSUE TITLE
Stop Shuffle or Visualisation while an Algorithm is running. 

### ISSUE THREAD

**Issue by gamedevCloudy** [TylerMommsen/sorting-visualizer#2]
The visualisation keeps running on the old algorithm or possibly both algorithms at once if you try to "Shuffle" or "Visualise" while one algorithm is running. 

- Do not shuffle if algorithm is running -> breaks the visualisation, end result is not sorted.
- Do not allow running another algorithm while one is running -> multiple algorithms run at same time

**Comment by gamedevCloudy** [comment]
I really like the sounds, reminded me of NES game like Mario

**Comment by TylerMommsen** [comment]
Thanks for pointing it out! Will get it fixed now.
